config/routes.rb
Rails.application.routes.draw do
  get 'profile/show'

  get 'profile/index'

  devise_for :users, controllers: { registrations: 'registrations' }

  
  root 'jobs#index'
  resources :jobs
  resources :users, only: :none do
    resources :profile, only: [:index]
    resources :logo,    only: [:create]
  end 
end

app/models/job.rb
class Job < ActiveRecord::Base
  enum status: [:active, :inactive, :archived]
  belongs_to :user

  validates_presence_of :user_id, :title, :content
  validates_length_of   :title, minimum: 5, maximum: 45
  validates_length_of   :content, minimum: 50, maximum: 50000
  sanitizes             :content
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :logo, LogoUploader

  has_many :jobs
  validates_presence_of :company_name
  validates_length_of   :company_name, minimum: 2, maximum: 15
  validates_length_of   :description, maximum: 1000
  validates_length_of   :url, maximum: 100
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :find_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = Job.all
  end

  def new
    @job = current_user.jobs.new
  end

  def create
    @job = current_user.jobs.new(job_params)

    if @job.save
      flash[:notice] = 'Your job has successfully created'
      redirect_to @job
    else 
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to @job
    else
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :content, :valid_till)
  end

  def find_job
    @job = Job.find(params[:id])
  end

end

app/controllers/logo_controller.rb
class LogoController < ApplicationController
  before_filter :authenticate_user!, only: [:create]

  def create
    @user = User.find(params[:user_id])
    @user.update_attributes(logo_params)
    redirect_to :back
  end

  private

  def logo_params
    params.require(:user).permit(:logo)
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @jobs = @user.jobs
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private
 
  def sign_up_params
    params.require(:user).permit(:email, :company_name,:password, :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:email, :company_name, :description, :url, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/logo_helper.rb
module LogoHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/jobs/_form.html.haml
= simple_form_for @job, html: { class: 'form-horizontal' } do |f|
  .form-group
    = f.input :title, input_html: { class: 'form-control' }
  .form-group
    = f.input :content, as: :ckeditor, input_html: { class: 'form-control', rows: 7, ckeditor: { toolbar: 'simple' } }
  %label Valid till  
  .row
    = f.input :valid_till, input_html: { class: 'form-control' }, label: false, start_year: Date.today.year
  %hr
  = f.button :submit, class: 'btn btn-success pull-right' 

app/views/jobs/_table.html.haml
%table.table
  %thead
    %tr
      %th Title
      %th Company
      %th Date
      %th Valid
      - if with_actions
        %th{width: '52px'}
  %tbody
    - @jobs.each do |job|
      %tr
        %td= link_to job.title, job
        %td 
          - unless job.user.logo.nil?
            = image_tag(job.user.logo_url(:thumb), class: 'thumb-logo')
          = link_to job.user.company_name, user_profile_index_path(job.user)
        %td= job.created_at.to_date
        %td= job.valid_till.to_date
        - if with_actions
          %td
            = link_to edit_job_path job do
              %span.glyphicon.glyphicon-pencil
            = link_to job_path(job), data: { confirm: "Are you sure?" }, method: :delete do
              %span.glyphicon.glyphicon-trash

app/views/jobs/edit.html.haml
.col-md-12
  .panel.panel-default
    .panel-heading
      %div
        %h4
          Edit Job:
          %b= @job.title
    .panel-body
      = render 'form'

app/views/jobs/index.html.haml
.col-md-12
  .panel.panel-default
    .panel-heading
      %h4 All Jobs
    .panel-body
      .table-responsive
        = render 'table', with_actions: false

app/views/jobs/new.html.haml
.col-md-12
  .panel.panel-default
    .panel-heading
      %h4 Create New Job
    .panel-body
      = render 'form'

app/views/jobs/show.html.haml
.col-md-12
  .panel.panel-default
    .panel-heading
      %h4= @job.title
      %a.btn.btn-default{href: jobs_path}
        %span.glyphicon.glyphicon-chevron-left
        Back to List
    .panel-body
      %p= sanitize @job.content

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'content-type'}
    %meta{charset: 'utf-8'}
    %meta{content: 'width=device-width, initial-scale=1, maximum-scale=1', name: 'viewport'}
    %title HRapp
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    /[if lt IE 9]
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  %body
    %nav.navbar.navbar-fixed-top.header
      .col-lg-12
        .navbar-header
          = link_to 'HRapp', root_path, class: 'navbar-brand'
          %button.navbar-toggle{'data-target' => '#navbar-collapse1', 'data-toggle' => 'collapse', type: 'button'}
            %i.glyphicon.glyphicon-search
        #navbar-collapse1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            -if user_signed_in?
              %li
                = link_to 'Add New Job', new_job_path
              %li
                %a.dropdown-toggle{'data-toggle' => "dropdown", href: '#'}
                  = current_user.email
                  %i.glyphicon.glyphicon-user
                %ul.dropdown-menu
                  %li
                    = link_to 'Profile', user_profile_index_path(current_user)
                    = link_to 'Sign out', destroy_user_session_path, method: :delete
            -else
              %li
                = link_to 'Sign in', new_user_session_path
              %li
                = link_to 'Sign up', new_user_registration_path
    #main.container
      .row
        = yield
        %br/
        .footer
          .clearfix
          %hr/
          .col-md-12.text-center
            %p
              Ruby on Rails, RSpec, Capybara
              %br/
              %a{:href => "https://github.com/lekishvili/hrapp", :target => "_ext"} Find me on GitHub
              